// stress/data.js
// stressIndex — индекс ударной гласной в слове (с нуля).

const NOUNS = [
    { word: "агент", stressIndex: 2 },
    { word: "алфавит", stressIndex: 5 },
    { word: "аэропорты", stressIndex: 5 },
    { word: "банты", stressIndex: 1 },
    { word: "бороду", stressIndex: 1 },
    { word: "бухгалтеров", stressIndex: 4 },
    { word: "вероисповедание", stressIndex: 9 },
    { word: "водопровод", stressIndex: 8 },
    { word: "газопровод", stressIndex: 8 },
    { word: "гражданство", stressIndex: 5 },
    { word: "дефис", stressIndex: 3 },
    { word: "дешевизна", stressIndex: 5 },
    { word: "диспансер", stressIndex: 7 },
    { word: "договоренность", stressIndex: 7 },
    { word: "документ", stressIndex: 5 },
    { word: "досуг", stressIndex: 3 },
    { word: "еретик", stressIndex: 4 },
    { word: "жалюзи", stressIndex: 5 },
    { word: "значимость", stressIndex: 2 },
    { word: "иксы", stressIndex: 0 },
    { word: "каталог", stressIndex: 5 },
    { word: "квартал", stressIndex: 5 },
    { word: "километр", stressIndex: 5 },
    { word: "конусов", stressIndex: 1 },
    { word: "корысть", stressIndex: 3 },
    { word: "краны", stressIndex: 2 },
    { word: "кремень", stressIndex: 4 },
    { word: "кремня", stressIndex: 5 },
    { word: "лекторов", stressIndex: 1 },
    { word: "локтя", stressIndex: 1 },
    { word: "локтей", stressIndex: 4 },
    { word: "лыжня", stressIndex: 4 },
    { word: "местностей", stressIndex: 1 },
    { word: "намерение", stressIndex: 3 },
    { word: "нарост", stressIndex: 3 },
    { word: "недруг", stressIndex: 1 },
    { word: "недуг", stressIndex: 3 },
    { word: "некролог", stressIndex: 6 },
    { word: "ненависть", stressIndex: 1 },
    { word: "нефтепровод", stressIndex: 9 },
    { word: "новостей", stressIndex: 6 },
    { word: "ногтя", stressIndex: 1 },
    { word: "ногтей", stressIndex: 4 },
    { word: "отзыв", stressIndex: 0, hint: "о книге" },
    { word: "отзыв", stressIndex: 3, hint: "посла" },
    { word: "отрочество", stressIndex: 0 },
    { word: "партер", stressIndex: 4 },
    { word: "портфель", stressIndex: 5 },
    { word: "поручни", stressIndex: 1 },
    { word: "приданое", stressIndex: 4 },
    { word: "призыв", stressIndex: 4 },
    { word: "свекла", stressIndex: 2 },
    { word: "сироты", stressIndex: 3 },
    { word: "созыв", stressIndex: 3 },
    { word: "сосредоточение", stressIndex: 8 },
    { word: "средства", stressIndex: 2 },
    { word: "статуя", stressIndex: 2 },
    { word: "столяр", stressIndex: 4 },
    { word: "таможня", stressIndex: 3 },
    { word: "торты", stressIndex: 1 },
    { word: "туфля", stressIndex: 1 },
    { word: "цемент", stressIndex: 3 },
    { word: "центнер", stressIndex: 1 },
    { word: "цепочка", stressIndex: 3 },
    { word: "шарфы", stressIndex: 1 },
    { word: "шофер", stressIndex: 3 },
    { word: "эксперт", stressIndex: 4 }
];

const ADJECTIVES = [
    { word: "верна", stressIndex: 4 },
    { word: "значимый", stressIndex: 2 },
    { word: "красивее", stressIndex: 4 },
    { word: "красивейший", stressIndex: 4 },
    { word: "кухонный", stressIndex: 1 },
    { word: "ловка", stressIndex: 4 },
    { word: "мозаичный", stressIndex: 4 },
    { word: "оптовый", stressIndex: 3 },
    { word: "прозорливый", stressIndex: 7 },
    { word: "прозорлива", stressIndex: 7 },
    { word: "сливовый", stressIndex: 2 }
];

const VERBS = [
    { word: "брала", stressIndex: 4 },
    { word: "бралась", stressIndex: 4 },
    { word: "взяла", stressIndex: 4 },
    { word: "взялась", stressIndex: 4 },
    { word: "влилась", stressIndex: 4 },
    { word: "ворвалась", stressIndex: 6 },
    { word: "воспринять", stressIndex: 7 },
    { word: "восприняла", stressIndex: 9 },
    { word: "воссоздала", stressIndex: 9 },
    { word: "вручит", stressIndex: 4 },
    { word: "гнала", stressIndex: 4 },
    { word: "гналась", stressIndex: 4 },
    { word: "добрала", stressIndex: 6 },
    { word: "добралась", stressIndex: 6 },
    { word: "дождалась", stressIndex: 6 },
    { word: "дозвонится", stressIndex: 6 },
    { word: "дозировать", stressIndex: 3 },
    { word: "ждала", stressIndex: 4 },
    { word: "жилось", stressIndex: 3 },
    { word: "закупорить", stressIndex: 3 },
    { word: "занять", stressIndex: 3 },
    { word: "занял", stressIndex: 1 },
    { word: "заняла", stressIndex: 5 },
    { word: "заняли", stressIndex: 1 },
    { word: "заперла", stressIndex: 6 },
    { word: "запломбировать", stressIndex: 11 },
    { word: "защемит", stressIndex: 5 },
    { word: "звала", stressIndex: 4 },
    { word: "звонит", stressIndex: 4 },
    { word: "кашлянуть", stressIndex: 1 },
    { word: "клала", stressIndex: 2 },
    { word: "клеить", stressIndex: 2 },
    { word: "кралась", stressIndex: 2 },
    { word: "кровоточить", stressIndex: 8 },
    { word: "лгала", stressIndex: 4 },
    { word: "лила", stressIndex: 3 },
    { word: "лилась", stressIndex: 3 },
    { word: "наврала", stressIndex: 6 },
    { word: "наделит", stressIndex: 5 },
    { word: "надорвалась", stressIndex: 8 },
    { word: "назвалась", stressIndex: 6 },
    { word: "накренится", stressIndex: 6 },
    { word: "налила", stressIndex: 5 },
    { word: "нарвала", stressIndex: 6 },
    { word: "начать", stressIndex: 3 },
    { word: "начал", stressIndex: 1 },
    { word: "начала", stressIndex: 5 },
    { word: "начали", stressIndex: 1 },
    { word: "обзвонит", stressIndex: 6 },
    { word: "облегчит", stressIndex: 6 },
    { word: "облегчить", stressIndex: 6 },
    { word: "облилась", stressIndex: 5 },
    { word: "обнялась", stressIndex: 5 },
    { word: "обогнала", stressIndex: 7 },
    { word: "ободрала", stressIndex: 7 },
    { word: "ободрить", stressIndex: 5 },
    { word: "ободрит", stressIndex: 5 },
    { word: "ободрится", stressIndex: 5 },
    { word: "ободриться", stressIndex: 5 },
    { word: "обострить", stressIndex: 6 },
    { word: "одолжить", stressIndex: 5 },
    { word: "одолжит", stressIndex: 5 },
    { word: "озлобить", stressIndex: 3 },
    { word: "оклеить", stressIndex: 3 },
    { word: "окружит", stressIndex: 5 },
    { word: "опошлить", stressIndex: 2 },
    { word: "осведомиться", stressIndex: 3 },
    { word: "осведомится", stressIndex: 3 },
    { word: "отбыла", stressIndex: 5 },
    { word: "отдала", stressIndex: 5 },
    { word: "откупорить", stressIndex: 3 },
    { word: "отозвала", stressIndex: 7 },
    { word: "отозвалась", stressIndex: 7 },
    { word: "опломбировать", stressIndex: 10 },
    { word: "перезвонит", stressIndex: 8 },
    { word: "перелила", stressIndex: 7 },
    { word: "плодоносить", stressIndex: 8 },
    { word: "пломбировать", stressIndex: 9 },
    { word: "повторит", stressIndex: 6 },
    { word: "позвала", stressIndex: 6 },
    { word: "позвонит", stressIndex: 6 },
    { word: "полила", stressIndex: 5 },
    { word: "положить", stressIndex: 5 },
    { word: "положил", stressIndex: 5 },
    { word: "понять", stressIndex: 3 },
    { word: "поняла", stressIndex: 5 },
    { word: "послала", stressIndex: 4 },
    { word: "прибыть", stressIndex: 4 },
    { word: "прибыл", stressIndex: 2 },
    { word: "прибыла", stressIndex: 6 },
    { word: "прибыли", stressIndex: 2 },
    { word: "принять", stressIndex: 4 },
    { word: "принял", stressIndex: 2 },
    { word: "приняла", stressIndex: 6 },
    { word: "приняли", stressIndex: 2 },
    { word: "рвала", stressIndex: 4 },
    { word: "сверлит", stressIndex: 5 },
    { word: "сняла", stressIndex: 4 },
    { word: "соврала", stressIndex: 6 },
    { word: "создала", stressIndex: 6 },
    { word: "сорвала", stressIndex: 6 },
    { word: "сорит", stressIndex: 3 },
    { word: "убрала", stressIndex: 5 },
    { word: "углубить", stressIndex: 5 },
    { word: "укрепит", stressIndex: 5 },
    { word: "черпать", stressIndex: 1 },
    { word: "исчерпать", stressIndex: 3 },
    { word: "щемит", stressIndex: 3 },
    { word: "щелкать", stressIndex: 1 }
];

const PARTICIPLES = [
    { word: "довезенный", stressIndex: 5 },
    { word: "загнутый", stressIndex: 1 },
    { word: "занятый", stressIndex: 1 },
    { word: "занята", stressIndex: 5 },
    { word: "запертый", stressIndex: 1 },
    { word: "заселенный", stressIndex: 5 },
    { word: "заселена", stressIndex: 7 },
    { word: "кормящий", stressIndex: 4 },
    { word: "кровоточащий", stressIndex: 8 },
    { word: "наживший", stressIndex: 3 },
    { word: "наливший", stressIndex: 3 },
    { word: "нанявшийся", stressIndex: 3 },
    { word: "начавший", stressIndex: 3 },
    { word: "начатый", stressIndex: 1 },
    { word: "низведенный", stressIndex: 6 },
    { word: "облегченный", stressIndex: 6 },
    { word: "ободренный", stressIndex: 5 },
    { word: "обостренный", stressIndex: 6 },
    { word: "отключенный", stressIndex: 6 },
    { word: "повторенный", stressIndex: 6 },
    { word: "поделенный", stressIndex: 5 },
    { word: "понявший", stressIndex: 3 },
    { word: "принятый", stressIndex: 2 },
    { word: "принята", stressIndex: 6 },
    { word: "прирученный", stressIndex: 6 },
    { word: "проживший", stressIndex: 4 },
    { word: "снята", stressIndex: 4 },
    { word: "согнутый", stressIndex: 1 },
    { word: "углубленный", stressIndex: 6 }
];

const GERUNDS = [
    { word: "закупорив", stressIndex: 3 },
    { word: "начав", stressIndex: 3 },
    { word: "начавшись", stressIndex: 3 },
    { word: "отдав", stressIndex: 3 },
    { word: "поняв", stressIndex: 3 },
    { word: "подняв", stressIndex: 4 },
    { word: "прибыв", stressIndex: 4 },
    { word: "создав", stressIndex: 4 }
];

const ADVERBS = [
    { word: "вовремя", stressIndex: 1 },
    { word: "добела", stressIndex: 5 },
    { word: "доверху", stressIndex: 1 },
    { word: "донизу", stressIndex: 1 },
    { word: "досуха", stressIndex: 1 },
    { word: "донельзя", stressIndex: 3 },
    { word: "загодя", stressIndex: 1 },
    { word: "засветло", stressIndex: 1 },
    { word: "затемно", stressIndex: 1 },
    { word: "надолго", stressIndex: 3 },
    { word: "ненадолго", stressIndex: 5 }
];

// Категории для экрана теории
const THEORY_CATEGORIES = [
    { title: 'Имена существительные', items: NOUNS },
    { title: 'Имена прилагательные', items: ADJECTIVES },
    { title: 'Глаголы', items: VERBS },
    { title: 'Причастия', items: PARTICIPLES },
    { title: 'Деепричастия', items: GERUNDS },
    { title: 'Наречия', items: ADVERBS }
];

// Общий словник для тренажёра — собирается из тех же массивов
const ORTHOEPIC_DICTIONARY = [
    ...NOUNS, ...ADJECTIVES, ...VERBS,
    ...PARTICIPLES, ...GERUNDS, ...ADVERBS
];

// ===== КОНСТАНТЫ СТАТИСТИКИ =====
const STATS_KEY = 'ege_stress_stats_v1';
const MAX_SESSIONS = 20;
const TOP_WORDS_LIMIT = 10;
const MIN_ANSWERS_FOR_SESSION = 3;